### ISSUE TITLE
Untangle the spaghetti

### ISSUE THREAD

**Issue by Macacoazul01** [lcuis/search_choices#100]
There are many widgets generated by functions and things being done more than one time in the code.

What makes it hard to understand and to fix and also leads to perceptive performance problems.

Creating this issue to help dealing with this.

- [x] Separate big classes
- [ ] Replace most or all widget functions for stateless or statefull widgets
- [ ] Reduce repetitive actions 
- [ ] Clean unnecessary parts

**Comment by lcuis** [comment]
The separate big classes point is part of the 2.2.0 release published to pub.dev .

**Comment by Macacoazul01** [comment]
Can you help with the item 2?
I'm a little lost in the code😅

**Comment by lcuis** [comment]
Yes, item 2 would be quite easy for me though, a bit time consuming. As I am in a rush on other projects right now, I will have to take care of this at a later stage. Though, I am confident this will be a major gain in performance. Thanks a lot for the suggestion.
