### ISSUE TITLE
Improve example app organization

### ISSUE THREAD

**Issue by Macacoazul01** [lcuis/search_choices#101]
It's hard to implement navigation logic and find out what's being done on the example app.

- [ ] Move materialApp higher in the widget three 
- [ ] Move search choices widget list to another file
- [ ] Organize the widget generation code to be more understandable

**Comment by Macacoazul01** [comment]
Can i delete the dropdown branch?

**Comment by lcuis** [comment]
Yes, this branch probably doesn't make much sense anymore since the reorganization of the code.
