### ISSUE TITLE
[Help] How to remove clear icon inside search input field 

### ISSUE THREAD

**Issue by erolkuluslu** [lcuis/search_choices#104]
I am trying to remove (or add a new functionality like going back the previous page directly) clear icon appears whenever I search something in the text field. As far as I understand, setting displayClearIcon to false only works for the one that is shown in second picture. Am I missing something or first picture clear icon cannot be removed ?
![image](https://user-images.githubusercontent.com/92374052/210254273-ae9d766c-7a0d-4d03-81e2-84a1a41d7ae7.png)
![image](https://user-images.githubusercontent.com/92374052/210255305-557c16d8-4270-4b21-b495-b8c5b3c693d6.png)

**Comment by lcuis** [comment]
Hello @erolkuluslu ,

Thanks for your question.

The following code using `clearSearchIcon` removes the icon in the search bar of the dialog (image 1):
```dart
SearchChoices.single(
        items: items,
        value: selectedValueSingleDialog,
        hint: "Select one",
        searchHint: "Select one",
        onChanged: (value) {
          setState(() {
            selectedValueSingleDialog = value;
          });
        },
        isExpanded: true,
        clearSearchIcon: Icon(Icons.clear,size:0),
      )
```

![image](https://user-images.githubusercontent.com/32125299/210273715-2a61e5ea-732d-4b24-b5c9-bb31239f8046.png)

**Comment by erolkuluslu** [comment]
Thanks a lot @lcuis it works now.

**Comment by lcuis** [comment]
You're welcome @erolkuluslu !
