### ISSUE TITLE
build failed after flutter upgrade

### ISSUE THREAD

**Issue by corioste** [lcuis/search_choices#106]
> Could not resolve all task dependencies for configuration ':app:profileCompileClasspath'.
   > Could not resolve project :search_choices.
     Required by:
         project :app
      > No matching configuration of project :search_choices was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile' but:
          - None of the consumable configurations have attributes.

**Comment by lcuis** [comment]
Hi @corioste ,

Thanks for letting me know. Can you please share the version of the `search_choices` plugin you are using? This can usually be found in the `pubspec.lock` file.

**Comment by corioste** [comment]
Hi @lcuis 

Thanks for the response

 search_choices:
    dependency: "direct main"
    description:
      name: search_choices
      sha256: d38e38beb237467e57ef3497c7cc04d1f4fb9fd7abc0eb2d8e5fab7e973ba29a
      url: "https://pub.dev"
    source: hosted
    version: "2.2.2"

**Comment by lcuis** [comment]
Sorry to read that it didn't work.

I am using the following without issues:
flutter --version
Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (7 days ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1

**Comment by lcuis** [comment]
Maybe there is something wrong with the gradle configuration? Which versions are you using?

**Comment by lcuis** [comment]
I don't have easy access right now but it is available in the example project.

**Comment by lcuis** [comment]
I have `ext.kotlin_version = '1.7.20'` here:
https://github.com/lcuis/search_choices/blob/a21e4f031cf828873101f7db9cf3b01076f2906c/example/android/build.gradle#L2
`classpath 'com.android.tools.build:gradle:7.0.0'` here:
https://github.com/lcuis/search_choices/blob/a21e4f031cf828873101f7db9cf3b01076f2906c/example/android/build.gradle#L9
And `distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip` here:
https://github.com/lcuis/search_choices/blob/a21e4f031cf828873101f7db9cf3b01076f2906c/example/android/gradle/wrapper/gradle-wrapper.properties#L6

I hope this will solve your issue.

**Comment by corioste** [comment]
I update my gradle to 6.9-all and some package to latest this fixed my issue

**Comment by lcuis** [comment]
Excellent, thanks for your confirmation @corioste !
