### ISSUE TITLE
Autofocus as option

### ISSUE THREAD

**Issue by slavap** [lcuis/search_choices#11]
See https://github.com/icemanbsi/searchable_dropdown/issues/58

**Comment by lcuis** [comment]
Hello @slavap ,

Sorry for the late reply. Quite busy days.

Can you please let me know whether the changes in release 1.0.16 cover your need regarding the autofocus parameter?

**Comment by slavap** [comment]
@lcuis Thank you very much! autofocus param works perfectly fine.

**Comment by lcuis** [comment]
Thanks a lot for your confirmation @slavap !
