### ISSUE TITLE
searchFn works on iPhone Simulator, but not iPhone (14 Pro Max)

### ISSUE THREAD

**Issue by joshwhitehouse** [lcuis/search_choices#112]
Hi, 

I'm using the SearchChoices 2.2.5 package from pub.dev, and am encountering a problem when using the searchFn. It works well on the iPhone Simulator, but search results aren't returned from it when running the app on an iPhone or iPad. I'm not sure what the problem is, using the debugger isn't giving me any hints as to the problem is.

I've attached screen shots so you can see what it looks like on the simulator, on my phone, along with my system I'm developing with and the flutter environment.

Thanks!

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-03 at 12 50 09](https://github.com/lcuis/search_choices/assets/2073241/e15f9f39-4387-44c2-beec-d114670f4ed7)
![Screenshot 2023-07-03 at 12 48 30](https://github.com/lcuis/search_choices/assets/2073241/5fbb962d-8c2d-41b0-958b-df5cd190e343)
<img width="1110" alt="flutterdoctor" src="https://github.com/lcuis/search_choices/assets/2073241/1df63f3b-1223-4d00-b2bc-cb93e4a446ba">
<img width="506" alt="hardware" src="https://github.com/lcuis/search_choices/assets/2073241/bc2d75aa-1fdc-41bc-9a53-f25d1055de27">

**Comment by lcuis** [comment]
Hi @joshwhitehouse ,

Thanks for reporting this issue.

It might be related to the way the search matching function is implemented.

Can you please share your code so that I can have a look?

**Comment by joshwhitehouse** [comment]
Hi,

Thanks for you reply!  I'm using pretty much the same search matching function you are.

Here is my implementation code. The Countries object is from a database, and I build Let me know if there is anything else you need. 

BTW, this is a terrific package you've developed, I have tried a couple of others, but yours is definitely better for my use!

Best,

Josh



```dart
class LocationsCountrySearchWidget extends StatelessWidget {
  const LocationsCountrySearchWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return SearchChoices<Countries>.single(
      style: TextStyle(fontSize: 14, color: blueColor),
      hint: "Select a Country",
      searchHint: "Select a Country",
      onChanged: (country) {
// set a value in the Provider store
      },
      items: getCountries(context: context),
      value: null,
      searchFn: (String keyword, items) {
        List<int> ret = [];
        if (items != null && keyword.isNotEmpty) {
          keyword.split(" ").forEach((k) {
            int i = 0;
            items.forEach((item) {
              if (!ret.contains(i) &&
                  k.isNotEmpty &&
                  (item.child
                      .toString()
                      .toLowerCase()
                      .contains(k.toLowerCase()))) {
                ret.add(i);
              }
              i++;
            });
          });
        }
        if (keyword.isEmpty) {
          ret = Iterable<int>.generate(items.length).toList();
        }
        return (ret);
      },
      dialogBox: true,
      isExpanded: true,
      clearSearchIcon: const Icon(
        Icons.backspace,
        color: Color.fromRGBO(33, 150, 243, 1),
      ),
    );
  }

  List<DropdownMenuItem<Countries>>? getCountries(
      {required BuildContext context}) {
    final realmServices = Provider.of<RealmServices>(context, listen: false);
    late RealmResults<Countries> countries = realmServices.realm
        .query<Countries>('TRUEPREDICATE SORT(country_name ASC)');

    List<DropdownMenuItem<Countries>> dropDownList = countries
        .map((country) => DropdownMenuItem(
              value: country,
              child: Text(country.countryName),
            ))
        .toList();
    return dropDownList;
  }
}
```

**Comment by lcuis** [comment]
Hi @joshwhitehouse ,

Thanks a lot for your message, this means a lot to me!

I was not able to try your code but I spotted a difference with the example that may explain the behavior you noticed:

In your code:
```dart
item.child // Using the item.child means you are taking the Text Widget instead of a String value. When using .toString() on it while in debug, this may work but not in release.
                      .toString()
                      .toLowerCase()
                      .contains(k.toLowerCase())
```

In the example:
```dart
item.value // The example uses the item.value which, in the example, is a String.
                        .toString()
                        .toLowerCase()
                        .contains(k.toLowerCase())
```

Since your `items` contains a value which contains a property called `countryName`, what you want to do is probably the following:

Likely working in your case:
```dart
item.value.countryName // In your case, the value.countryName is likely the String you want to search against.
                        .toString()
                        .toLowerCase()
                        .contains(k.toLowerCase())
```

I hope this will solve your issue.

**Comment by joshwhitehouse** [comment]
I just noticed the same thing myself! I had already changed it to item.value.countryName instead of the item.child (which is a Text). It worked on the simulator just now using item.value.countryName, I'm going to test it on the iPhone right now, and will confirm it works as soon as I do. Many, many thanks!

**Comment by lcuis** [comment]
That's great, thanks for letting me know. Fingers crossed for the release/device test.

**Comment by joshwhitehouse** [comment]
Yes! that fixed it fine on the device as well! Thanks so much for having a look!

Best, 

Josh

**Comment by joshwhitehouse** [comment]
closed

**Comment by lcuis** [comment]
Thanks to you Josh for this great news!
