### ISSUE TITLE
Android fails with gradle 8

### ISSUE THREAD

**Issue by sweetfa** [lcuis/search_choices#114]
With gradle 8 the android/build.gradle requires a namespace to be defined.

i.e.

android {
  compkeSdkversion 33
  namespace 'li.kod.search_choices'
  ....

**Comment by lcuis** [comment]
Hello @sweetfa ,

Thanks for raising this!

I tried to follow the steps mentioned here:
https://stackoverflow.com/questions/76182805/gradle-error-linked-to-namespace-on-build-gradle-file

I added the namespace to the android/build.gradle file:
```
android {
    namespace 'li.jod.search_choices'

    compileSdkVersion 33
...
}
```


But I still get this error:

```
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
    namespace 'com.example.namespace'
}

If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
```

**Comment by samalapsy** [comment]
I think I once got this error and I used my app's applicationId as the namespace value. Can you give that a try?

**Comment by lcuis** [comment]
@sweetfa I know this is a very old topic but I believe the recent changes with release 2.2.9 and 2.2.8 address this issue. If not, please reopen. Thanks!
