### ISSUE TITLE
Remove the margin/padding in sides & redesign options buttons

### ISSUE THREAD

**Issue by blue492** [lcuis/search_choices#117]
Hi, 
I want that my implemented searchHint be full width with blue background.  I have already implemented the searchHint, and I need just to remove all margin/padding in all Search_choices showDialog sides

I need to redesign the options with a grey background to be like image 2. 

Is it possible to remove the margin/padding in all sides to be like image 2? I couldn't do it because I didn't found any option to remove margin/padding in all sides
How to redesign DropdownMenuItem to be like image 2

[Image 1](https://github.com/lcuis/search_choices/assets/66443263/d9080c32-0638-45e4-96df-bce2168842d4): is current design when I use Search_choices
[Image 2](https://github.com/lcuis/search_choices/assets/66443263/fd1a346f-d4d4-466b-a644-f1550f8068fd): is the desired design which I do it in photoshop.

Thanks

Image 1
![image 1](https://github.com/lcuis/search_choices/assets/66443263/d9080c32-0638-45e4-96df-bce2168842d4)

Image 2
![image 2](https://github.com/lcuis/search_choices/assets/66443263/fd1a346f-d4d4-466b-a644-f1550f8068fd)

**Comment by blue492** [comment]
@lcuis do you have any solutions, thanks

**Comment by lcuis** [comment]
Hello @blue492 .

Sorry for the delay. I am on holiday without access to my coding hardware. Maybe some past closed issues contain the solution to your issue?
Otherwise, I'll try to get back to you as soon as I can.

**Comment by lcuis** [comment]
Hi @blue492 ,

Here is the example without changing anything:
![image](https://github.com/lcuis/search_choices/assets/32125299/88b5b938-1afc-40fe-905d-cb6756c0e95e)

Here is the example generated with the code below:

![image](https://github.com/lcuis/search_choices/assets/32125299/69293ae0-8e70-43e5-9d40-224a7e747802)

```dart
      SearchChoices.single(
        items: items,
        value: selectedValueSingleDialog,
        hint: "Select one",
        searchHint: "Select one",
        onChanged: (value) {
          setState(() {
            selectedValueSingleDialog = value;
          });
        },
        isExpanded: true,
        displayItem: (item, selected) {
          return (
            Expanded(
              child: item,
            )
        );
        },
        buildDropDownDialog: (
          Widget titleBar,
          Widget searchBar,
          Widget list,
          Widget closeButton,
          BuildContext dropDownContext,
        ) {
          return (AnimatedContainer(
            padding: MediaQuery.of(dropDownContext).viewInsets,
            duration: const Duration(milliseconds: 100),
            child: Card(
              margin: EdgeInsets.symmetric(vertical: 0, horizontal: 0),
              child: Container(
                padding: EdgeInsets.symmetric(vertical: 0, horizontal: 0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    titleBar,
                    searchBar,
                    list,
                    closeButton,
                  ],
                ),
              ),
            ),
          ));
        },
      )
```

I hope this is a good starting point to achieve what you are trying to do.

**Comment by blue492** [comment]
@lcuis Thanks for reply, I want that the modal be like [image 2] (https://github.com/lcuis/search_choices/assets/66443263/fd1a346f-d4d4-466b-a644-f1550f8068fd)

Your solution is full size in the screen with no margin, and dropdownbutton is not designed as I want.
Thanks for help

**Comment by lcuis** [comment]
Thanks for your reply @blue492 .

I agree, my example is not exactly as your image2. However, I believe that the code I shared with you is a good starting point. With a few adaptations, you can certainly reach a situation much closer to the desired outcome. If something is not possible because the plugin lacks flexibility, please let me know.

**Comment by blue492** [comment]
@lcuis thanks for your buildDropDownDialog solution, I could design my items by displayItem function.

I hope you continue upgrade SearchChoices

**Comment by lcuis** [comment]
Hi @blue492 , I also hope I will keep upgrading SearchChoices. Thanks for your message!
