### ISSUE TITLE
Update value from outside the plugin doesn't work

### ISSUE THREAD

**Issue by abdugaliyev** [lcuis/search_choices#120]
Mi 8 Android 10
sdk: '>=3.0.2 <4.0.0'
"Update value from outside the plugin": Column(
        children: [
          SearchChoices.single(
            items: items,
            value: selectedValueUpdateFromOutsideThePlugin,
            hint: const Text('Select One'),
            searchHint: const Text(
              'Select One',
              style: TextStyle(fontSize: 20),
            ),
            onChanged: (value) {
              setState(() {
                selectedValueUpdateFromOutsideThePlugin = value;
              });
            },
            isExpanded: true,
          ),
          TextButton(
            child: const Text("Select dolor sit"),
            onPressed: () {
              setState(() {
                selectedValueUpdateFromOutsideThePlugin = "dolor sit";
              });
            },
          ),
        ],
      ),
      setState(() {
                selectedValueUpdateFromOutsideThePlugin = "dolor sit";
              });
              
              this work fine, but doesnt render changes

**Comment by lcuis** [comment]
Hi @abdugaliyev ,

Sorry to answer so extremely late.

Can you please explain why you say the example doesn't render changes?

The "Update value from outside the plugin" example in the example app does render the changes when the external button is pressed.

Your example also works the same if you just remove the astonishing part at the end.

Cheers.
