### ISSUE TITLE
jdk version

### ISSUE THREAD

**Issue by 15611217599** [lcuis/search_choices#128]
kotlin {
    jvmToolchain(18)
}
this

* What went wrong:
Could not determine the dependencies of task ':search_choices:bundleLibCompileToJarDebug'.
> Could not create task ':search_choices:compileDebugJavaWithJavac'.
   > Failed to calculate the value of task ':search_choices:compileDebugJavaWithJavac' property 'javaCompiler'.
      > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=18, vendor=any, implementation=vendor-specific} for WINDOWS on x86_64.
         > No locally installed toolchains match and toolchain download repositories have not been configured.

**Comment by DEVELOPBYSHUBH** [comment]
Same here, i am not able make an build.

**Comment by DEVELOPBYSHUBH** [comment]
Same here,

**Comment by nilkanth-sudo** [comment]
Hi @15611217599 @DEVELOPBYSHUBH 
just comment or remove this 3 line and try to run
it's worked in my system

**Comment by pnilkanth12** [comment]
Hi @15611217599  @DEVELOPBYSHUBH 
just comment or remove this 3 line and try to run
it's worked in my system

**Comment by lcuis** [comment]
You are having an issue that would be solved if someone removed those three lines from the plugin?

**Comment by Lukaalishi** [comment]
we need help plz

**Comment by lcuis** [comment]
Hi @15611217599 , @Lukaalishi , @pnilkanth12 , @DEVELOPBYSHUBH 

I am very sorry for the inconvenience. I hope release 2.2.11 solves this issue for you. I applied the fix mentioned by @pnilkanth12 , thanks!
