### ISSUE TITLE
Programatically set the value after the widget is created?

### ISSUE THREAD

**Issue by peterd1954** [lcuis/search_choices#13]
I need to set the value to be shown after the widget is created, depending upon a selection of another widget.
How can I do that please?
Best regards,
Peter.

**Comment by lcuis** [comment]
Hi @peterd1954 ,
I believe that example “Update value from outside the plugin” in the example/lib/main.dart file can help you with what you need.

**Comment by peterd1954** [comment]
Hi @lcuis ,
thanks for the quick response! 
Still having the same problem.

I have two SearchChoices.single.
First one is loaded with 'Jobs'. This DropDownMenuItems in this list never changes. The user can select whichever item they want from the list.
Second SearchChoices.single list is loaded dynamically with 'Tasks' when the user makes a choice from the first list. This list can have a different number of items loaded, depending on the users choice in the first list. So the second list might have 4 items or it might have 20 items.

The error occurs when:
1. The user selects a menu item from the first SearchChoices.single widget list and the dynamically loaded second SearchChoices.single widget list contains 20 'Tasks'..
2. The user then selects a menu item from the second SearchChoices.single widget list, and the menu item choice is a high one, say menu item 20.
3. Then the user changes their mind and AGAIN attempts to select a menu item from the FIRST SearchChoices.single widget list, and this time they select a menu item which dynamically builds a short list for the second  SearchChoices.single widget,  which contains only 4 menu items. 
4. I am resetting the value as you have suggested, and I was doing so before, but this does not seem to make a difference.
5. I get this error consistently with this scenario.
"RangeError (index): Invalid value: Not in range 0..1, inclusive: 2"
6. If the user chooses a first SearchChoices.single widget list which builds the second SearchChoices.single widget list with the same number (or more) of menu items as has previously been selected there is no error. The value in the second SearchChoices.single widget list is cleared.
7. I would like a way to be able to simply clear the value and the index in a SearchChoices widget with an external option if possible.
Thanks for your help @lcuis

**Comment by lcuis** [comment]
Hello @peterd1954 ,

Do you clear the selected task from the first list `onChanged` function before the `setState` call?

**Comment by peterd1954** [comment]
Hi @lcuis ,

Inside the setState call I set the new value on the first list, cleared the second list and the selected value in the second list, then rebuilt the second list.

**Comment by peterd1954** [comment]
The setState call was in the onChanged on the first list.

**Comment by lcuis** [comment]
I'm sorry for what is happening with this range error. Maybe you should try to run step by step with a debugger to see what is happening. My second advice would be to clear the selected task as early as possible.

**Comment by peterd1954** [comment]
Hey @lcuis ,
solved it, my mistake!!
Thanks for your quick attention. 
Cheers,

**Comment by lcuis** [comment]
I'm glad it worked. Thanks for the confirmation!
