### ISSUE TITLE
Flutter 3.27 warnings

### ISSUE THREAD

**Issue by 23doors** [lcuis/search_choices#130]
```
Package search_choices:linux references search_choices:linux as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of search_choices to either avoid referencing a default implementation via `platforms: linux: default_package: search_choices` or add an inline implementation to search_choices via `platforms: linux:` `pluginClass` or `dartPluginClass`.

Package search_choices:macos references search_choices:macos as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of search_choices to either avoid referencing a default implementation via `platforms: macos: default_package: search_choices` or add an inline implementation to search_choices via `platforms: macos:` `pluginClass` or `dartPluginClass`.

Package search_choices:windows references search_choices:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of search_choices to either avoid referencing a default implementation via `platforms: windows: default_package: search_choices` or add an inline implementation to search_choices via `platforms: windows:` `pluginClass` or `dartPluginClass`.
```

I guess `default_package` lines should be removed in pubspec.yaml.

**Comment by lcuis** [comment]
Hi @23doors ,

Thanks for bringing this to my attention.

Indeed, I get the warning message with the up to date version of Flutter.
The message is surprising because there is a pluginClass for each platform.

Maybe the solution is what you are proposing but I am not able to build for the web for now. This may be a separate issue. I will look into this as soon as I can.

**Comment by alexandr-efimov** [comment]
Hi, 
looks like it causes build error with Flutter 3.27 (not only warning):

> > Failed to build iOS app
> Could not build the precompiled application for the device.
> Error (Xcode): Package search_choices:linux references search_choices:linux as the default plugin, but it does not provide an inline implementation.

**Comment by DKAC** [comment]
+1

**Comment by lcuis** [comment]
It looks like I have network issues preventing CI/CD running without this kind of error:
```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 6320 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
Error: fatal: early EOF
Error: fatal: fetch-pack: invalid index-pack output
Warning: Git fetch failed with exit code 128, back off 8.908 seconds before retry.
```
I don't remember this happening to me that severely in the past.
I will publish anyway to pub.dev .

**Comment by lcuis** [comment]
@23doors @alexandr-efimov @DKAC @blue492 ,

I was finally able to find a solution for the network issue.
Version 2.3.1 is published which allowed me to compile for macos, android, ios and web.

Please let me know if all is good for you.

Cheers!

**Comment by 23doors** [comment]
Just tested 2.3.1 - looks like that warning is gone, thanks! Closing
