### ISSUE TITLE
SearchChoices.single increases container size after selecting value

### ISSUE THREAD

**Issue by ettiennelr** [lcuis/search_choices#15]
Hi

I have a container that has size X before selecting a value. Then after selecting value the container increases in size. How can I keep the size the same always?
Attached is an example:
1 - Top drop-down, I have selected a value
2 - Bottom drop-down I have not yet selected.

Also, the text after selecting is always right-aligned.

they are both configured the same way

![Screenshot_1592140398](https://user-images.githubusercontent.com/8167415/84594494-e7ef6a80-ae52-11ea-8eef-1e928334c431.png)

**Comment by lcuis** [comment]
Hi @ettiennelr ,

Maybe the answers to this issue can give you some hints on how to solve yours?

https://github.com/icemanbsi/searchable_dropdown/issues/35

Please, let me know whether it worked or not.

**Comment by ettiennelr** [comment]
Hi @lcuis 

Thank you so much!!!

**Comment by lcuis** [comment]
Excellent, thanks a lot @ettiennelr for your feedback!
