### ISSUE TITLE
Add customization option for Clear button.

### ISSUE THREAD

**Issue by slavap** [lcuis/search_choices#17]
In case no selection is made, I need an option to not display clear button (currently it is displayed as disabled, which is quite confusing). This new option should display clear button only if there is selection.

![image](https://user-images.githubusercontent.com/4129763/85344783-7bedb180-b4a5-11ea-9b18-dccde36f10f5.png)

Also it should be possible to specify position of clear button, before or after dropdown button:
![image](https://user-images.githubusercontent.com/4129763/85345026-2e257900-b4a6-11ea-9028-ade39e39b7e7.png)

**Comment by lcuis** [comment]
Hi @slavap ,

There is a workaround that should allow you to do something close to what you require if not exactly what you require. This would involve using:
- `displayClearIcon: false` parameter.
- `selectedAggregateWidgetFn` parameter (assuming you are using the multiple version of the constructor) to include a clear button in the required area if the selected list is not empty. See example [here](https://github.com/lcuis/search_choices/blob/48d3fb3071e8d3ede7b9749dc140ce5ff7cd0a70/example/lib/main.dart#L932).

Please, let me know if there is something not clear about those suggestions.

**Comment by slavap** [comment]
@lcuis 
Thanks, it works exactly as you described.
```dart
selectedAggregateWidgetFn: (List<Widget> list) {
        return (Row(children: [
          Expanded(
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              //Text("${list.length} items selected"),
              Wrap(children: list),
            ]),
          ),
          if (isNotEmpty(list))
            Column(mainAxisAlignment: MainAxisAlignment.center, children: [
              Container(
                padding: EdgeInsets.only(right: 8),
                child: InkWell(onTap: () => onChanged([]), child: Icon(Icons.clear)),
              ),
            ]),
        ]));
      },
```

**Comment by lcuis** [comment]
Thanks for the code and the confirmation!
