### ISSUE TITLE
Make padding adjustable.

### ISSUE THREAD

**Issue by slavap** [lcuis/search_choices#18]
Currently padding is hardcode, and actually it is a little bit excessive by default, i.e. padding: EdgeInsets.all(10.0),
Please make it adjustable.

![image](https://user-images.githubusercontent.com/4129763/88994501-64bc9380-d29d-11ea-8779-461c90882c48.png)

**Comment by lcuis** [comment]
Hello @slavap ,

Thanks for the suggestion. It is indeed not flexible at the moment. However, the workaround explained here usually solves the padding questions:
https://github.com/icemanbsi/searchable_dropdown/issues/35

Please pet me know if that works for you too.

**Comment by slavap** [comment]
@lcuis I think that using transform: Matrix4.translationValues(-10,0,0), for just adjusting padding is overkill and hack :-) Please add normal way to define it.

**Comment by lcuis** [comment]
Well, as I said, this is a workaround. So, yes, it may be that one day, a better way to handle padding with search_choices will exist.

**Comment by slavap** [comment]
@lcuis sure, as workaround it is ok.

**Comment by lcuis** [comment]
I believe this was solved by #27 .
Feel free to reopen if needed.
