### ISSUE TITLE
add title And validation

### ISSUE THREAD

**Issue by devZakariya** [lcuis/search_choices#20]
how can i add a title to the dropdown button and validation

**Comment by lcuis** [comment]
Hello @devZakariya ,

To add a label to the Widget, see the "Multi custom display dialog" example available [here](https://github.com/lcuis/search_choices/blob/48d3fb3071e8d3ede7b9749dc140ce5ff7cd0a70/example/lib/main.dart#L329) and with result visible [here](https://searchchoices.jod.li/) (4th example).
Here is the description of the `label` parameter:
```
label String|Widget|Function with parameter: value returning String|Widget displayed above the selected item or the hint if none.
```

![image](https://user-images.githubusercontent.com/32125299/86485518-cd712880-bd50-11ea-90ff-e6fd7ae3fa37.png)

**Comment by devZakariya** [comment]
Thank you a lot

**Comment by lcuis** [comment]
You're welcome @devZakariya , enjoy!

**Comment by devZakariya** [comment]
but how can i add label with single dropdown ?
