### ISSUE TITLE
Needed possibility to configure dialog size and even dialog itself.

### ISSUE THREAD

**Issue by slavap** [lcuis/search_choices#22]
Currently there is a property: menuConstraints, but it is ignored in case of dialogBox = true
As result on large screens dialog takes almost all available space, which looks bad. 
Please add property dialogConstraints to be able to limit dialog size.
Also it would be **absolutely** perfect if option for overriding showDialog() call is added, like:
```dart
OnShowDialog onShowDialog;

typedef OnShowDialog  = Future Function(BuildContext context, Widget menuWidget);
```
That way it will be possible to configure showDialog() exactly the way it is needed for my application, even replacing standard dialog to custom one.

**Comment by lcuis** [comment]
Hello @slavap ,
Is this an improvement proposal to add dialogConstraints or to add onShowDialog? Or does one solve the other?

**Comment by slavap** [comment]
@lcuis better to add onShowDialog, it will be more powerful customization. But nothing wrong with adding both, for simple cases dialogConstraints could be easier to use.

**Comment by lcuis** [comment]
Sorry for the late reply.

I hope version 2.0.2 solves this issue as well as #23 with the possibility to control the layout of the dropdown dialog through `buildDropDownDialog` function as shown in example app.

If it doesn't solve, please reopen this issue.
