### ISSUE TITLE
Margin and padding override for menu/dialog content

### ISSUE THREAD

**Issue by slavap** [lcuis/search_choices#23]
Currently it is hardcoded:
```dart
child: Card(
        color: widget.menuBackgroundColor,
        margin: EdgeInsets.symmetric(
            vertical: widget.dialogBox ? 10 : 5,
            horizontal: widget.dialogBox ? 10 : 4),
        child: Container(
          constraints: widget.menuConstraints,
          padding: EdgeInsets.symmetric(vertical: 15, horizontal: 15),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              titleBar(),
              searchBar(),
              list(),
              closeButtonWrapper(),
            ],
          ),
        ),
      ),
```
Need properties: menuMargin and menuPadding to be able to override these hardcoded values.

![image](https://user-images.githubusercontent.com/4129763/88994930-4c00ad80-d29e-11ea-93dd-f2aa3d54275c.png)

**Comment by lcuis** [comment]
Hi @slavap ,

It seems to me that your suggestion is quite similar to #18 .
Also, wouldn't this solve the main request of #22 ?

**Comment by slavap** [comment]
@lcuis #22 is about ability to override showDialog(), but dialog content will be passed already constructed as input parameter. And if margin/padding are already hardcoded in constructed content you cannot change them in override.

**Comment by lcuis** [comment]
Sorry for the late reply.

I hope version 2.0.2 solves this issue as well as #22 with the possibility to control the layout of the dropdown dialog through `buildDropDownDialog` function as shown in example app.

If it doesn't solve, please reopen this issue.
