### ISSUE TITLE
keyboard autofocus option should be customized

### ISSUE THREAD

**Issue by tsuncp** [lcuis/search_choices#25]
sometimes we dun want to show the keyboard automatically. Better to allow customize the autofocus option of the searchBar?

**Comment by lcuis** [comment]
This is a good potential improvement, thanks @tsuncp

**Comment by lcuis** [comment]
Hi @tsuncp ,

I don't remember when this was implemented but autofocus is a parameter that does what are asking for.

I'll wait a bit for your confirmation before closing this issue.

Cheers,

Louis.

**Comment by lcuis** [comment]
Closing for now, feel free to reopen if needed.
