### ISSUE TITLE
Select all doesnt work and Is this library still maintained?

### ISSUE THREAD

**Issue by Raphael-Jose-Ferraro-IRForever** [lcuis/search_choices#28]
Is this library still maintained?

My code:
List<String> bairros = List<String>();
List<String> bairrosEscolhidos = List<String>();
List<int> bairrosEscolhidosInt = List<int>();

SearchChoices.multiple(
                      doneButton: (selectedItemsDone, doneContext) {
                        return (RaisedButton(
                            color: temaPadrao.primaryColor,
                            onPressed: () {
                              Navigator.pop(doneContext);
                            },
                            child: Text(
                              'Salvar',
                              style: TextStyle(color: Colors.white),
                            )));
                      },
                      items:
                          bairros.map<DropdownMenuItem<String>>((String value) {
                        return DropdownMenuItem<String>(
                          value: value,
                          child: Text(value),
                        );
                      }).toList(),
                      selectedItems: bairrosEscolhidosInt,
                      selectedValueWidgetFn: (item) {
                        return (Center(
                            child: Card(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(5),
                                  side: BorderSide(
                                    color: temaPadrao.primaryColor,
                                    width: size.paddingPequeno / 4,
                                  ),
                                ),
                                margin: EdgeInsets.all(size.paddingPequeno),
                                child: Padding(
                                  padding: EdgeInsets.all(size.paddingPequeno),
                                  child: Text(item.toString()),
                                ))));
                      },
                      hint: Padding(
                        padding: EdgeInsets.all(size.paddingMedio),
                        child: Text('Selecione os Bairros e Distritos'),
                      ),
                      style: TextStyle(fontSize: size.textPequeno),
                      searchHint: Text(
                        'Selecione os Bairros e Distritos',
                        style: TextStyle(fontSize: size.textPequeno),
                      ),
                      onChanged: (value) {
                        setState(() {
                          bairrosEscolhidosInt.clear();
                          bairrosEscolhidos.clear();
                          bairrosEscolhidosInt = value;
                          for (var x in value) {
                            bairrosEscolhidos.add(cidades[x]);
                          }
                        });
                      },
                      closeButton: (selectedItemsClose) {
                        return Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: <Widget>[
                            RaisedButton(
                                onPressed: () {
                                  setState(() {
                                    bairrosEscolhidos.clear();
                                    bairrosEscolhidosInt.clear();
                                    bairrosEscolhidosInt.addAll(
                                        Iterable<int>.generate(bairros.length)
                                            .toList());
                                  });
                                },
                                child: Text("Selecionar Todos")),
                            RaisedButton(
                                onPressed: () {
                                  setState(() {
                                    bairrosEscolhidos.clear();
                                    bairrosEscolhidosInt.clear();
                                  });
                                },
                                child: Text("Limpar Seleção")),
                          ],
                        );
                      },
                      isExpanded: true,
                    ),

**Comment by lcuis** [comment]
Yes, this library is still maintained.

Here is a simplified version of your code for which the select all and select none buttons work:

```dart
  List bairros = ["first item","second item"];
  List<int> bairrosEscolhidosInt = [];
...
SearchChoices.multiple(
        items:
        bairros.map<DropdownMenuItem>((dynamic value) {
          return DropdownMenuItem(
            value: value,
            child: Text(value),
          );
        }).toList(),
        selectedItems: bairrosEscolhidosInt,
        onChanged: (value) {
          setState(() {
            bairrosEscolhidosInt = value;
          });
        },
        closeButton: (selectedItemsClose, closeContext, Function updateParent) {
          return Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              ElevatedButton(
                  onPressed: () {
                    setState(() {
                      selectedItemsClose.clear();
                      selectedItemsClose.addAll(Iterable<int>.generate(bairros.length).toList());
                    });
                    updateParent(selectedItemsClose);
                  },
                  child: Text("Selecionar Todos")),
              ElevatedButton(
                  onPressed: () {
                    setState(() {
                      selectedItemsClose.clear();
                    });
                    updateParent(selectedItemsClose);
                  },
                  child: Text("Limpar Seleção")),
            ],
          );
        },
        isExpanded: true,
      )
```

Can you please let me know whether I can close this issue?

Thanks.

**Comment by Raphael-Jose-Ferraro-IRForever** [comment]
Thanks bro. Its working now!

**Comment by lcuis** [comment]
Excellent, thanks for the confirmation!
