### ISSUE TITLE
Hi, you will support null safety?

### ISSUE THREAD

**Issue by Raphael-Jose-Ferraro-IRForever** [lcuis/search_choices#31]
Hi, you will support null safety? This package is very good, pls update him!

**Comment by lcuis** [comment]
Hello @Raphael-Jose-Ferraro-IRForever ,

Thanks for this request. Version 2.0.0 now supports sound null safety.

Can you please let me know whether this works fine for you and whether I can close this request?

Cheers.

**Comment by Raphael-Jose-Ferraro-IRForever** [comment]
Thank you man! Good news!
