### ISSUE TITLE
working on emulator but not on apk version

### ISSUE THREAD

**Issue by Aryan-Solanki** [lcuis/search_choices#36]

**Comment by lcuis** [comment]
Dear @Aryan-Solanki ,

Can you please provide a minimal yet complete example code for your issue and a description with at least the output of flutter doctor and an explanation of your issue (expected and effective behaviors to the very least)?

This plugin works fine on several Android apks for me.

**Comment by Aryan-Solanki** [comment]
i used it like..


SearchChoices.single(
                    autofocus: true,
                    items: city(),
                    value: selectedValueSingleDialog,
                    hint: "Search for your city",
                    onChanged: (value) {
                      if (value != null) {
                        selected_city = value.data;
                        UserSimplePreferences.setCity(selected_city);
                        if (backlink == "moderator") {
                          Navigator.pushReplacement(
                            context,
                            MaterialPageRoute(
                                builder: (context) => modHomePage(
                                      selectedItemPosition: 2,
                                    )),
                          );
                        } else if (backlink == "registration") {
                          Navigator.pushReplacement(
                            context,
                            MaterialPageRoute(
                                builder: (context) => regHomePage()),
                          );
                        } else if (backlink == "beneficiary") {
                          Navigator.pushReplacement(
                            context,
                            MaterialPageRoute(
                                builder: (context) => HomePage(
                                      selectedItemPosition: 2,
                                    )),
                          );
                        }
                      }

                      // selectedValueSingleDialog = value;
                    },
                    isExpanded: true,
                  ),

-----------------------------------

this is city() function


import 'package:flutter/material.dart';
List<DropdownMenuItem> city(){
  return [DropdownMenuItem(
    child: Text("Delhi"),
    value: Text("Delhi"),
  ),
    DropdownMenuItem(
      child: Text("Kolkata"),
      value: Text("Kolkata"),
    ),
    DropdownMenuItem(
      child: Text("Mumbai"),
      value: Text("Mumbai"),
    ),
];
}

**Comment by Aryan-Solanki** [comment]
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 2.0.5 at D:\flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\sdk
    • Java binary at: D:\Codes\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Codes\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\solan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

**Comment by Aryan-Solanki** [comment]
when i m running on emulator or through mobile search works ..meaning if i type "d" it shows all results that have d in it..
but when i build apk it does works

**Comment by lcuis** [comment]
Dear @Aryan-Solanki ,

Thank you very much for those details. I will have a look at them as soon as possible and let you know. It is likely to be within 24 hours.

**Comment by lcuis** [comment]
Hello @Aryan-Solanki ,

One thing I just noticed that may cause the behavior you witness is that your DropdownMenuItem value should be a String and not a Text Widget for the search feature to work properly. This would become something like this:

```dart

import 'package:flutter/material.dart';
List city(){
return [DropdownMenuItem(
child: Text("Delhi"),
value: "Delhi",
),
DropdownMenuItem(
child: Text("Kolkata"),
value: "Kolkata",
),
DropdownMenuItem(
child: Text("Mumbai"),
value: "Mumbai",
),
];
}
```

I was not able to test this exact code but this has a lot more chances to work as such.

**Comment by Aryan-Solanki** [comment]
thanks man its now working :)

**Comment by lcuis** [comment]
Great! Thanks a lot for letting me know!
