### ISSUE TITLE
Call API (Future function) when dialog opened?

### ISSUE THREAD

**Issue by tranvanphay** [lcuis/search_choices#43]
Is it possible to call API to get data of search dialog when I tap to open it ?

**Comment by lcuis** [comment]
Hello @tranvanphay ,

Thanks for your question.

The API results are loaded directly from the server as soon as the Widget is tapped to open the dialog or the menu in the future related examples of the `search_choices` plugin.
Examples so far:
- Single dialog paged future
- Multi menu paged future
- Single dialog future custom empty list

Please let me know if you meant or need something else.

**Comment by tranvanphay** [comment]
> Hello @tranvanphay ,
> 
> Thanks for your question.
> 
> The API results are loaded directly from the server as soon as the Widget is tapped to open the dialog or the menu in the future related examples of the `search_choices` plugin.
> Examples so far:
> 
> * Single dialog paged future
> * Multi menu paged future
> * Single dialog future custom empty list
> 
> Please let me know if you meant or need something else.

Successfully, great library

**Comment by lcuis** [comment]
Excellent. Thanks a lot for your confirmation and for your message!

**Comment by tranvanphay** [comment]
I have try to custom your library, but I don't know why i meet this problem, when the keyboard is show, search choice be rebuild. Did you meet this problem

https://user-images.githubusercontent.com/42576241/128199207-beb68089-8897-493a-94a4-2a335ae1a18d.mp4

**Comment by lcuis** [comment]
Thanks for reporting this!

Maybe this is because of a fix I deployed today with version 2.0.7 ?
I’ll check as soon as possible.

**Comment by lcuis** [comment]
It also works fine with Android with latest version 2.0.7:

https://user-images.githubusercontent.com/32125299/128254803-88b2c083-5fd6-49ae-b382-c5080a8ac9c8.mov

Sorry I cannot reproduce your issue @tranvanphay .

Is there anything I can do to help?
