### ISSUE TITLE
onTap function doesn't work 

### ISSUE THREAD

**Issue by EbrahimMosaaed** [lcuis/search_choices#49]
`   items: dropdownElemnts?.data?.sectors!.map((Sector value) {
            return DropdownMenuItem<String>(
              onTap: () {
                print('clicked');
              },
              value: value.id.toString(),
              child: Text(value.name!),
            );
          }).toList(),`

> 
Actually i have two issues the first one ,the  search feature doesn't work when the value and child pramters take different values as shown..with the below code search feature will work
`    value: value.name,
              child: Text(value.name!),`

the second issue onTap function doesn't work at all  
>

**Comment by lcuis** [comment]
Hello @EbrahimMosaaed ,

For the `onTap` not working on the item, I am not surprised this doesn’t work. Though, this may be an interesting improvement. If the `onTap` of the item is not null, the widget could execute it.

For the search working on the item value string, maybe this issue would help you:
https://github.com/lcuis/search_choices/issues/37#issuecomment-852035040

**Comment by lcuis** [comment]
Hello @EbrahimMosaaed ,

Here is an example working for the onTap with the latest plugin version 2.0.8:
```dart
          String printable=new String.fromCharCodes(wordPair.characters.map<int>((element)=>element.codeUnitAt(0)).toList());
          items.add(DropdownMenuItem(
            child: Text(wordPair),
            value: wordPair,
            onTap: (){print("You tapped $printable !!!");},
          ));
```

This only works with non future items.

**Comment by EbrahimMosaaed** [comment]
@lcuis 
onTap function works perfectly fine, with the latest version 2.0.8.

Thanks .👍

**Comment by lcuis** [comment]
You're welcome @EbrahimMosaaed !
Thanks to you for the request and the confirmation!
