### ISSUE TITLE
Center `searchHint`

### ISSUE THREAD

**Issue by franciscocpg** [lcuis/search_choices#55]
Is there a way to center `searchHint`? I tried the snippet below but it didn't work.
```dart
searchHint: Center(child: Text("Select one")),
```

**Comment by lcuis** [comment]
Hello @franciscocpg ,

Thanks for your question.

I would have expected your solution to address your requirement.

I am not able to investigate right now. I will have to come back to you later on this. Sorry.

**Comment by lcuis** [comment]
I had to wrap the Widget in an `Expanded` one to center the `searchHint`:
```dart
        searchHint: Expanded(child:Text("Select one",textAlign: TextAlign.center,)),
```
This also works:
```dart
        searchHint: Expanded(child: Center(child:Text("Select one",))),
```

Can you please confirm that it works for you?

**Comment by franciscocpg** [comment]
Both solutions work fine for me.

Thank you.

**Comment by lcuis** [comment]
Thank you for the confirmation!
