### ISSUE TITLE
Can SearchChoices handle a list of a few thousand items?

### ISSUE THREAD

**Issue by GroovinChip** [lcuis/search_choices#6]
I'm building a client application for the Mastodon platform and users are supposed to be able to select any registered instance to log into. What I'm currently doing to achieve this is calling https://instances.social/api/doc/#api-Instances-ListInstances, storing all the instances in a list, and giving that to `SearchChoices.single`. But that response is paginated in the order of a few thousand pages of instances, and I'm wondering if SearchChoices can handle a list made of all the instances in those few thousand pages - right now I'm only passing the first page. Would this be a problem?

**Comment by lcuis** [comment]
Hello @GroovinChip ,

Thanks for your question.
Indeed, pagination is needed to break down the list when too many items are expected.
So far, I didn't use SearchChoices for this purpose, however, I may implement a solution in the future depending on my needs.
Instead, I used the very good [SmartRefresher](https://github.com/peng8350/flutter_pulltorefresh) for more dynamically handled network lists (reload, pagination,...).

Maybe, SearchChoices will evolve in this direction one day?
I will update this thread if this happens.

**Comment by GroovinChip** [comment]
Thanks so much for your prompt response. How do you use SmartRefresher in conjunction with SearchChoices? I'm not seeing a way I can use both together.

**Comment by lcuis** [comment]
My pleasure @GroovinChip .

In fact, I don't know how to use SmartRefresher with SearchChoices together and I don't think this is possible without code adaptations. I just use SearchChoices for small lists and SmartRefresher for long ones.

**Comment by GroovinChip** [comment]
Gotcha. Thanks very much! The only ways I can think of to accomplish my goal are to try and take all the instance names for all the pages and make one huge list and see what happens, or to go back to trying to use the search endpoint to dynamically add results to SearchChoices as the user types. Which I found pretty difficult. Thanks again for your help!

**Comment by GroovinChip** [comment]
Turns out this widget can handle a huge list of items with no trouble at all! Closing issue.

**Comment by lcuis** [comment]
Hi @GroovinChip !

The evolution I mentioned earlier was needed for one of my projects.

Since version 2.0.4 and later, the `SearchChoices` plugin supports pagination and Future/network/API/webservice calls.
The example is meant to work with PHP-CRUD-API based webservice using a non-web Flutter client. However, the example can be adapted for many other situations.
https://github.com/lcuis/search_choices#single-dialog-paged-future
