### ISSUE TITLE
FutureSelectedValues not select when given as Custom object.

### ISSUE THREAD

**Issue by MrShamp** [lcuis/search_choices#60]
While given futureSelectedValues in list `isItemSelected` returning false. 
Function is trying to check if list contain item or not.  But as different future request have different hash code was generated for new objects. and it will return false. 

The check should be based on some converting to hash or something.

Need your assistance! Thanks.

ps. 
File name: search_choices.dart
Function line number: 2394
Conflicting line number: 2401

<img width="589" alt="Screenshot 2022-01-06 at 6 59 07 PM" src="https://user-images.githubusercontent.com/45307265/148394049-2da19fa7-1a84-4622-ab76-855752fe62f8.png">
.

**Comment by lcuis** [comment]
Hello @MrShamp 

Thanks for raising this issue.

Does your object have a toString() method?
Does this method return a stable and unique identification string?

**Comment by MrShamp** [comment]
It can return a stable identification string. I can modify it my Class.

**Comment by lcuis** [comment]
@MrShamp thanks for your comment!
I hope this will solve your issue.

**Comment by MrShamp** [comment]
It will complicated for different types of Classes. Defined unique protocol for each class.

**Comment by lcuis** [comment]
Hi @MrShamp ,

If you are working on a simpler solution or if you have an idea for simplification, I might be interested.

**Comment by MrShamp** [comment]
Hi @lcuis,
I am able to find solution on my end. By overriding, `operator == `& `Hash Code`.
If somehow we able to extend the `TypeCasted`  class to override these above methods. we can solve it. As List.contain check for HashCodes. 

Reference: https://stackoverflow.com/questions/67751745/flutter-dart-list-how-to-check-if-a-list-contains-an-object

Do let me know if I can help you anyway!.

Thanks

**Comment by lcuis** [comment]
Thanks for your proposal and explanations @MrShamp !

If I understand correctly, for the following line from `search_choices.dart` to work here, we need the selectable item class to have the `==` and `hashCode` defined?
```dart
return (widget.futureSelectedValues!.contains(value));
```

If so, maybe an example in the example `main.dart` file would help?

Otherwise, I don't see a reliable way to guess from the plugin the hash code of undefined objects. Is there?

**Comment by MrShamp** [comment]
Yes! I didn't find any reliable way to guess from the plugin the hash code of undefined objects. You are right.

You can add in documentation about overriding `== ` and `hashCode`  for future concerns.  Or we can put warning or comment on that parameter.

**Comment by MrShamp** [comment]
I am going to close this issue. Thanks for prompt reply.
