### ISSUE TITLE
Style - remove line below input field

### ISSUE THREAD

**Issue by DKAC** [lcuis/search_choices#62]
Is there a way to remove the thin line? In general, it would be nice, if one could use InputDecorators to change the style of the Widget.

**Comment by lcuis** [comment]
Hello @DKAC ,

Thanks for your question and suggestion.

There is an `InputDecorator` parameter but this is probably not what you are looking for. Try the `underline` parameter instead.

**Comment by DKAC** [comment]
Hi @lcuis,

thanks for the hint... putting an empty Widget into the underline parameter, is working fine (with null the default underline is shown).

**Comment by lcuis** [comment]
Thank you for the confirmation @DKAC !
