### ISSUE TITLE
Search not working when value is a class

### ISSUE THREAD

**Issue by Musty-dev** [lcuis/search_choices#66]
I want to select a simple class but the search is not working, what I'm doing wrong?

Here is my code:

`SearchChoices.single(
items: this.datas.map((data) => DropdownMenuItem<KeyValueModel>(
                                child: Text(data.value),
                                value: data,
                              )).toList(),
                              value: _selectedValue,
                              hint: "Select one",
                              searchHint: "Select one",
                              onChanged: (KeyValueModel value) {
                                setState(() {
                                  //log("selected value: "+selectedValue);
                                  _selectedValue = value;
                                  log("c");
                                });
                              },
                              isExpanded: true,
                              isCaseSensitiveSearch: false
                            )`

**Comment by lcuis** [comment]
Hello @Musty-dev ,

Thanks for your question.

The search works on custom objects by doing a match on whatever the object returns  as a `.toString()' .

So, if your `item.toString()` returns for example `Hello World!` and you search for `rl`, the search will match.
