### ISSUE TITLE
Search Not Working at all

### ISSUE THREAD

**Issue by dandoii** [lcuis/search_choices#67]
Hi, I can't seem to get the search functionality working. Here's the code below.
buildDefectChoice() {
    if (defects!.isNotEmpty) {
      List<DropdownMenuItem> listChoices = [];
      if (isPest) {
        for (var item in pests!) {
          listChoices.add(DropdownMenuItem(child: Text(item)));
        }
      } else {
        for (var item in defects!) {
          listChoices.add(DropdownMenuItem(child: Text(item)));
        }
      }

      return Column(children: [
        Center(child: Text("What are you Scouting for?")),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            TextButton(
                onPressed: () {
                  setState(() {
                    isPest = true;
                  });
                },
                child: Text("Pest",
                    style:
                        TextStyle(color: isPest ? Colors.green : Colors.grey))),
            TextButton(
                onPressed: () {
                  setState(() {
                    isPest = false;
                  });
                },
                child: Text("Defect",
                    style:
                        TextStyle(color: !isPest ? Colors.green : Colors.grey)))
          ],
        ),
        SearchChoices.single(
          
          items: listChoices,
          hint: isPest ? "Select a Pest" : "Select a Defect",
          searchHint: "Select one",
          onChanged: (value) {
            setState(() {
              selectedDefects = value;
            });
          },
          isExpanded: true,
        )
      ]);
    } else {
      return circularProgress();
    }
  }

**Comment by lcuis** [comment]
Hello @dandoii ,

Thanks for your question.

For the search to work, the DropDownMenuItem must have a value and the value must have a `.toString()` method which will be used for the search.
