### ISSUE TITLE
InputDecoration how to adding 

### ISSUE THREAD

**Issue by sajiyabro98** [lcuis/search_choices#69]
can apply search input box but not i want to that

Look my UI =>
![image](https://user-images.githubusercontent.com/40933349/154867277-b6e56e15-f774-404a-b719-bcc30bd71258.png)

```
kInputDecoration(String labelText)=> InputDecoration(
  isDense: true,
  filled: true,
  fillColor: Colors.green.shade100,
  border: OutlineInputBorder(),
  labelText: labelText,
);
```

Please help me

**Comment by lcuis** [comment]
Maybe you are looking for the "Multi custom display dialog" example with the underline parameter:
‘‘‘dart
underline: Container(
          height: 1.0,
          decoration: BoxDecoration(
              border:
                  Border(bottom: BorderSide(color: Colors.teal, width: 3.0))),
        ),
‘‘‘

**Comment by sajiyabro98** [comment]
I applied this code after look

![image](https://user-images.githubusercontent.com/40933349/155044796-3204ad2a-fcb9-4fe5-8d14-491fdd6aba85.png)

full code -
```
Obx(() => SearchChoices.single(
            items: projectController.siteSubCategoriesList.value.map((item) {
              return DropdownMenuItem(
                  value: item.siteSubCategoryName,
                child: Text(item.siteSubCategoryName!)
              );
            }).toList(),
            value: projectController.siteSubCategories.value.toString(),
            hint: "Site SubCategories Name",
            onChanged: (value) =>projectController.set_siteSubCategories_name(value.toString()),
            isExpanded: true,
              underline: Container(
                height: 1.0,
                decoration: BoxDecoration(
                    border:
                    Border(bottom: BorderSide(color: Colors.teal, width: 3.0))),
              )
          )),
```
But I want to designing like this

![image](https://user-images.githubusercontent.com/40933349/155044995-40b11f64-9698-4208-9ce7-068ae6e50a97.png)

![image](https://user-images.githubusercontent.com/40933349/155044998-a9bc944d-aa16-473a-915e-58c5e8796a89.png)

**Comment by lcuis** [comment]
Sorry, @sajiyabro98 , I got it wrong.

I added the parameter `fieldPresentationFn` for that purpose to version 2.0.18 of the `search_choices` plugin. I hope this will fulfil your need.

Here is an example:
![image](https://user-images.githubusercontent.com/32125299/155068785-53143eca-1cce-4078-883f-f05b152724db.png)
```dart
        fieldPresentationFn: (Widget fieldWidget, {bool? selectionIsValid}) {
          return Container(
            padding: const EdgeInsets.all(12.0),
            child: InputDecorator(
              decoration: InputDecoration(
                labelText: 'Label',
                isDense: true,
                filled: true,
                fillColor: Colors.green.shade100,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(10)),
                ),
              ),
              child: fieldWidget,
            ),
          );
        },
```

**Comment by sajiyabro98** [comment]
@lcuis Again i have problem... :(

I couldn't update this 
[[UNIDENTIFIED]](https://pub.dev/packages/search_choices/score)
when I manually added with I got error
pubspec.yaml 
```
search_choices:
    git:
      url: https://github.com/lcuis/search_choices.git
```
![image](https://user-images.githubusercontent.com/40933349/155218784-41a627ea-04f6-4d98-82d0-ebcdf3a5009b.png)

**Comment by lcuis** [comment]
Hello @sajiyabro98 ,

This means you have the same issue as described in #70 . Sorry about that.
This is happening because of this #69 update.
It looks like it is affecting more developers than expected. I would like to find a solution.

**Comment by lcuis** [comment]
Version 2.0.19 of search_choices solves the issue #70 you faced with the thumbVisibility parameter error. Sorry about that one.
It also contains the change with the fieldPresentationFn desired for #69 .

I would like to add that you shouldn't need to use git and url tags in your pubspec.yaml because I keep github repository and pub.dev in sync. This should work in your pubspec.yml file:
```yaml
    search_choices:
```

**Comment by sajiyabro98** [comment]
@lcuis  Thanks so much for
your plugging and it is I had been best one.

**Comment by lcuis** [comment]
> @lcuis  Thanks so much for
> your plugging and it is I had been best one. 

Thanks for your message @sajiyabro98 , I'm glad you're enjoying this plugin.
