### ISSUE TITLE
Version 2.0.18 broken

### ISSUE THREAD

**Issue by DKAC** [lcuis/search_choices#70]
Hi there,

setting the version of search_choices explicitly to 2.0.17, everything builds fine, but when switching to 2.0.18, I get the following error on build (flutter 2.10.2):

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib\main.dart:1
/[C:/Users/.../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/search_choices-2.0.18/lib/search_choices.dart:2513:9](): Error: No named parameter with the name 'thumbVisibility'.
        thumbVisibility: widget.itemsPerPage == null ? false : true,
        ^^^^^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.
../…/material/scrollbar.dart:75
  const Scrollbar({
        ^^^^^^^^^
3

FAILURE: Build failed with an exception.
```

(I would really like to switch to 2.0.18 because it's adding a feature I was actually waiting for... :))

**Comment by ImmortalKDN1** [comment]
I also have the same ERROR!

**Comment by lcuis** [comment]
Hi @DKAC and @ImmortalKDN1 ,

Thanks for reporting this issue.

I was forced to change this scrolling parameter after a flutter upgrade.

You can either block the search_choices version as you mentioned or upgrade to the latest flutter version with `flutter upgrade`.

Sorry for the inconvenience.

**Comment by DKAC** [comment]
I did a "flutter clean" and "flutter upgrade" and "flutter packages upgrade", unfortunately, the error remains the same

```
**Flutter 2.10.2** • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (4 days ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2
```

@ImmortalKDN1 did you perform a flutter upgrade to 2.10.2?

**Comment by ImmortalKDN1** [comment]
But I have to say that everything was working fine yesterday!

**Comment by lcuis** [comment]
I'm using flutter 2.11.0-0.0.pre.634 master with dart 2.17.0-125.0.dev

That would explain why I was forced to do this change while you cannot compile with it.

However, this should only affect latest version (.18).

Also, the CI/CD on GitHub is also using a blocking version.

**Comment by DKAC** [comment]
I am fine with using 2.0.17. In general, however, I think it would be better to just require the current stable version of flutter. Give it a thought...
And thank you very much for your hard work on this great package!

**Comment by lcuis** [comment]
> > I'm using flutter 2.11.0-0.0.pre.634 master with dart 2.17.0-125.0.dev
> > 
> > That would explain why I was forced to do this change while you cannot compile with it.
> > 
> > However, this should only affect latest version (.18).
> > 
> > Also, the CI/CD on GitHub is also using a blocking version.
> 
> I was using search_choices v 2.0.14 when I got the problem! After that I tried the versions 2.0.18 & 2.0.17 and got the same problem! It was when I tried the version 1.0.17 that it was fine... It could be coming from me, but I don't know where since I didn't change my code after yesterday!

Sorry about this. I am not sure either where exactly this is coming from.

**Comment by lcuis** [comment]
> I am fine with using 2.0.17. In general, however, I think it would be better to just require the current stable version of flutter. Give it a thought...
> And thank you very much for your hard work on this great package! 

I agree, I don't know why GitHub CI/CD is not using this same version of flutter/dart.
Also, it would be much more convenient if deprecating was done with a grace period for backward compatibility. Unless I missed something, I find this particular handling a bit abrupt.

Again, sorry for this. I'm glad you're enjoying this package.

**Comment by DKAC** [comment]
Should I leave this ticket open until the flutter stable channel works with 2.0.18, so others can find it easily?

**Comment by lcuis** [comment]
> Should I leave this ticket open until the flutter stable channel works with 2.0.18, so others can find it easily? 

Yes, @DKAC , this is a good idea. It can be closed as soon as the stable version of flutter becomes compatible with the latest version of search_choices again. If I come to notice this myself, I can close it too.
Thanks!

**Comment by lcuis** [comment]
Version 2.0.19 of search_choices solves this #70 issue with the thumbVisibility parameter error.
I changed the CI/CD flutter channel in the .github/workflows/main.yml file as stable. Same on my machine with command `flutter channel stable` followed by `flutter upgrade`.

**Comment by DKAC** [comment]
Just tested 2.0.19 successfully (had to upgrade kotlin and gradle though)! Thanks a lot for the quick solution.

**Comment by lcuis** [comment]
Thanks a lot for the confirmation!
