### ISSUE TITLE
SearchChoices.single constructor missing underline

### ISSUE THREAD

**Issue by TraXIcoN** [lcuis/search_choices#71]
SearchChoices.single is missing the underline property

Using SearchChoices version **^2.0.17**

> FIx: I think just the addition of the below line in the return statement of SearchChoices.single is required:
> `underline: underline,`

**Comment by lcuis** [comment]
Hi @TraXIcoN ,

Is this line correcting your issue in the latest version?
https://github.com/lcuis/search_choices/blob/master/lib/search_choices.dart#L608

**Comment by TraXIcoN** [comment]
My bad I was not on the latest version. Thanks for the update👍

**Comment by lcuis** [comment]
Thanks for the confirmation @TraXIcoN !
