### ISSUE TITLE
[enhancement] add adjustable close/clear icon to search text field

### ISSUE THREAD

**Issue by gslender** [lcuis/search_choices#73]
as per title

**Comment by lcuis** [comment]
Hello @gslender ,

Thanks for your enhancement proposal.

I hope this is what you had in mind:

![image](https://user-images.githubusercontent.com/32125299/177567034-0fc2e86f-8849-41f2-9fdc-2494912d156e.png)

```dart
        clearSearchIcon: Icon(
          Icons.backspace,
          color: Colors.teal,
        ),
```

It will soon be available with version 2.0.21 .

**Comment by gslender** [comment]
Looks good 👍

**Comment by lcuis** [comment]
Thanks !

**Comment by lcuis** [comment]
Closing as this is on pub.dev with version 2.0.21 .
Feel free to reopen.
