### ISSUE TITLE
[request] customizable dialog box size

### ISSUE THREAD

**Issue by Macacoazul01** [lcuis/search_choices#77]
When we use the `dialogBox: true `, to show the list of added items, the dialog occupies the whole screen.

It would be nice if existed a way of controlling the height/width of it

**Comment by lcuis** [comment]
Thanks, this is indeed missing.

**Comment by lcuis** [comment]
There is a workaround with this example:
https://github.com/lcuis/search_choices#Single-dialog-custom-dialog

Still, a dedicated argument would be more convenient.

**Comment by Macacoazul01** [comment]
Any chances of developing this argument?

**Comment by lcuis** [comment]
I would like to add this argument but I am not likely to have the time to do this in the coming months sadly.

**Comment by Macacoazul01** [comment]
I can try to implement it so then you only will have to check the pull request. Where on the code is the part that shows the dialog?

**Comment by lcuis** [comment]
That would be sweet of you, thanks @Macacoazul01 .
I can then check, merge your PR and publish to pub.dev .
Don't hesitate to update the Contributors section of the readme file.

The dialog box is built from the `build` function here:
https://github.com/lcuis/search_choices/blob/97e6b7ee7be4fc500ef8318b5cb752ddf0d23be3/lib/search_choices.dart#L2084

If the `buildDropDownDialog` argument is null, the following is returned:
```dart
AnimatedContainer(
      padding: MediaQuery.of(dropdownDialogContext).viewInsets,
      duration: const Duration(milliseconds: 300),
      child: Card(
        color: widget.menuBackgroundColor,
        margin: EdgeInsets.symmetric(
            vertical: widget.dialogBox ? 10 : 5,
            horizontal: widget.dialogBox ? 10 : 4),
        child: Container(
          constraints: widget.menuConstraints,
          padding: EdgeInsets.symmetric(vertical: 15, horizontal: 15),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              titleBar(),
              searchBar(),
              listWithPagination(),
              closeButtonWrapper(),
            ],
          ),
        ),
      ),
    )
```

**Comment by lcuis** [comment]
Version 2.0.20 has been published to pub.dev:
https://pub.dev/packages/search_choices

Thanks @Macacoazul01 !
