### ISSUE TITLE
iOS Compile error - 'search_choices_for_push-Swift.h' file not found

### ISSUE THREAD

**Issue by jaspervdbijl** [lcuis/search_choices#8]
Getting the following error on building for iOS

XCode Version 11.3.1 
Tried to compile example project

.../pub-cache/hosted/pub.dartlang.org/search_choices-1.0.12/ios/Classes/SearchChoicesForPushPlugin.m:8:9: fatal error: 'search_choices_for_push-Swift.h' file not found
    #import "search_choices_for_push-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

flutter doctor (tested on stable and beta channels )

⇒  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale en-ZA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] Connected device (3 available)

• No issues found!

**Comment by lcuis** [comment]
Hello @jaspervdbijl ,

Thank you very much for letting me know. Indeed, I have the same issue right now. I'm looking for a solution and will let you know as soon as I learn something new.

**Comment by lcuis** [comment]
Hello again @jaspervdbijl ,

The easy fix for me was to do the following in the plugin folder and the example folder:
```sh
flutter clean
rm -rf ios
```
And then do the following in the plugin folder:
```sh
flutter create .
```

I am not sure why this is happening. I will try to release a new version that fixes this issue.

Thanks again for letting me know.

**Comment by lcuis** [comment]
Some files were missing. Latest version 1.0.13 fixes this issue by adding those files. Could you please let me know whether this is also the case for you or whether we cannot close this issue?

**Comment by jaspervdbijl** [comment]
Verified working on 1.0.13
Thanks

**Comment by lcuis** [comment]
Thanks @jaspervdbijl for the confirmation!
