### ISSUE TITLE
example/lib/main.dart

### ISSUE THREAD

**Issue by jihan007** [lcuis/search_choices#83]
example/lib/main.dart seems not updated. If I copy and paste it in main.dart it produces several error. Can you please check and update the example file so that we can have a quick look of visual usage.

**Comment by lcuis** [comment]
Hi @jihan007 ,

Thanks for reaching out on this issue.

I am using Android Studio.

I just created a new Flutter project.

I added those lines to the `dependencies` section of the `pubspec.yaml` file:
```yaml
  search_choices:
  http:
```
I clicked on the "Pub get" text button above the `pubspec.yaml` file.

I pasted the following file to replace the whole `lib/main.dart`:
https://pub.dev/packages/search_choices/example

I clicked the debug button.

The example app appeared on my connected and selected phone.

I stopped and clicked the run button.

I got the same successful result.

I did the same (debug and run) with the following file as the source:
https://github.com/lcuis/search_choices/blob/master/example/lib/main.dart

I got again twice the same successful result:
![image](https://user-images.githubusercontent.com/32125299/178091882-9686621a-44e2-41c6-8e03-d25db6f47024.png)

Please let me know if there is anything I can do as the example `main.dart` file seems to work fine from my perspective.

**Comment by jihan007** [comment]
Thanks a lot. Its working now.

**Comment by lcuis** [comment]
Excellent, thanks for letting me know @jihan007 .
