### ISSUE TITLE
Search not working in release mode.

### ISSUE THREAD

**Issue by saraswatisharma** [lcuis/search_choices#86]

**Comment by lcuis** [comment]
Just to be on the safe side, here are the results of the automated tests run for each release on Flutster:
![image](https://user-images.githubusercontent.com/32125299/188371587-5dd28c91-7068-4c85-9e57-8d6ce183755b.png)

The result says success for the 40 tests.
Here is where the automated testing is called:
https://github.com/lcuis/search_choices/blob/6d70c86173a977e5d3600efd4cd78a83c96e4b3a/.github/workflows/main.yml#L52
