### ISSUE TITLE
Multi dialogue paged future search hint

### ISSUE THREAD

**Issue by rob-mur** [lcuis/search_choices#88]
Hi

I think I've found a bug/at least something that should be better documented.

If you want to have filters/sorting in a multi dialogue paged future (and potentially the menu variant too) then it isn't enough to fill out futureSearchFn and futureSearchFilterOptions/futureSearchOrderOptions. You **also** need to set searchHint: "".

Otherwise the buttons to filter/sort don't show at the top of dialogue. I had ran into this because it wasn't clear that a search hint would be necessary in order to add filter buttons. 

To recreate the problem, simply clone the examples project and remove the searchHint: "", in Multi dialog paged future.

**Comment by lcuis** [comment]
Thanks a lot @rob-mur , well spotted. I look forward to try to reproduce and fix this issue.

**Comment by lcuis** [comment]
I was able to reproduce the issue. The sort and filter buttons don't appear when searchHint is not provided. I intend to fix this.

**Comment by lcuis** [comment]
I was able to fix but this is not fully tested with flutster tests. Thus, I didn't publish to pub.dev yet. This should be in version 2.1.2 . Thanks @rob-mur !

**Comment by rob-mur** [comment]
No problem at all, well done for the speedy turn around!

**Comment by lcuis** [comment]
Hello @rob-mur ,

Version 2.1.2 has just been released to pub.dev .

Cheers!

**Comment by lcuis** [comment]
Closing. Feel free to reopen if needed.
