### ISSUE TITLE
 No named parameter with the name 'thumbVisibility'.         thumbVisibility: widget.itemsPerPage == null ? false : true,

### ISSUE THREAD

**Issue by omar-hadek** [lcuis/search_choices#89]

**Comment by lcuis** [comment]
Salam @omar-hadek , mar7ba,

Maybe issue #70 can help you with this issue?

Otherwise, maybe I can help myself if you send your flutter, dart and search_choices plugin versions.

**Comment by omar-hadek** [comment]
@lcuis  Chokran 

i've tried the latest version

search_choices: ^2.1.1 

--------Flutter ----------------------------------
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by lcuis** [comment]
Thanks for the details @omar-hadek ,

From #70 , I know there is a flutter version between 2.10.2 and 2.11.0 that forced some abrupt changes with this thumbVisibility parameter. From the issue you raised, it seems that flutter version 2.10.5 also has this issue.
It seems to relate to this commit and probably started with version 2.11.0 :
https://github.com/flutter/flutter/commit/03da339ffe1fa1f45beac136725cb6560514c67e

The options I see for you are the following:
a) Upgrade your flutter version to at least 2.11.0 . I use 3.0.5 with success.
b) Or fix search_choices version to 2.0.17 .
c) Or fork search_choices and change the only use of thumbVisibility in search_choices.dart into isAlwaysShown .

I would recommend option a) and I am sorry for the inconvenience.

**Comment by lcuis** [comment]
Closing. Feel free to reopen if needed.
