### ISSUE TITLE
Facing issue when dialog is set false than I cannot use buildDropDownDialog.

### ISSUE THREAD

**Issue by krButani** [lcuis/search_choices#93]
Facing issue when dialog is set false than I cannot use buildDropDownDialog. 

we need to redesign dropdown menu. its showing below error

buildDropDownDialog and dropDownDialogPadding must be null ifdialogBox == false
'package:search_choices/search_choices.dart':
Failed assertion: line 1070 pos 13: 'dialogBox ||
                (dropDownDialogPadding == null && buildDropDownDialog == null)'

**Comment by lcuis** [comment]
Hi @krButani ,

Thanks for your message.

Indeed, I was able to make the following example work once I removed the assertion condition:
```dart
SearchChoices.single(
        items: items,
        value: selectedValueSingleMenu,
        hint: "Select one",
        searchHint: null,
        onChanged: (value) {
          setState(() {
            selectedValueSingleMenu = value;
          });
        },
        dialogBox: false,
        isExpanded: true,
        menuConstraints: BoxConstraints.tight(const Size.fromHeight(350)),
        buildDropDownDialog: (
            Widget titleBar,
            Widget searchBar,
            Widget list,
            Widget closeButton,
            BuildContext dropDownContext,
            ) {
          return (AnimatedContainer(
            padding: MediaQuery.of(dropDownContext).viewInsets,
            duration: const Duration(milliseconds: 300),
            child: SizedBox(
              height: 400,
              child: Card(
                margin: const EdgeInsets.symmetric(vertical: 30, horizontal: 40),
                child: Container(
                  padding:
                  const EdgeInsets.symmetric(vertical: 35, horizontal: 45),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      titleBar,
                      searchBar,
                      list,
                      closeButton,
                    ],
                  ),
                ),
              ),
            ),
          ));
        },
      )
```

This is challenging the necessity for this assertion condition.
I will thus publish a new version as soon as possible once automated testing has run successfully.

Cheers.

**Comment by lcuis** [comment]
Version 2.1.7 got the problematic assertion condition removed.

If you think that this issue can be closed, feel free to close it @krButani .
If you think there is more to be done, can you please let me know?
Otherwise, I can close this issue myself in a few days.
Thanks again for raising it!

**Comment by krButani** [comment]
We need one more thing that is we need to close dropdown menu programmatically. It means once user open dropdown menu than he is focusing other control that time no need to select from dropdown.

**Comment by lcuis** [comment]
Hi @krButani ,

Can you please create a new issue with this need?
An example would help me to understand I think.

**Comment by krButani** [comment]
Okay
